name: Build and Release Native Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (Semantic version, e.g. 1.2.3)'
        required: true
        type: string
      notes:
        description: 'Release notes'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64

    outputs:
      release_notes: ${{ steps.set_release_notes.outputs.release_notes }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache JavaFX JMods
        uses: actions/cache@v3
        with:
          path: javafx-jmods
          key: javafx-jmods-${{ matrix.os }}-${{ matrix.arch }}-24.0.1

      - name: Download JavaFX JMods 24.0.1 (if cache miss)
        if: steps.cache-javafx-jmods.outputs.cache-hit != 'true'
        run: |
          OS="${{ matrix.os }}"
          ARCH="${{ matrix.arch }}"

          case "$OS" in
            ubuntu-latest)
              if [ "$ARCH" = "arm64" ]; then
                JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_linux-aarch64_bin-jmods.zip"
              else
                JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_linux-x64_bin-jmods.zip"
              fi
              ;;
            macos-latest)
              if [ "$ARCH" = "arm64" ]; then
                JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_osx-aarch64_bin-jmods.zip"
              else
                JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_osx-x64_bin-jmods.zip"
              fi
              ;;
            windows-latest)
              JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_windows-x64_bin-jmods.zip"
              ;;
            *)
              echo "Unsupported OS: $OS"
              exit 1
              ;;
          esac

          echo "Downloading JavaFX JMods from $JFX_URL"
          curl -L "$JFX_URL" -o javafx-jmods.zip
          unzip javafx-jmods.zip -d javafx-jmods
          rm javafx-jmods.zip
        shell: bash
        id: cache-javafx-jmods

      - name: Set JAVAFX_JMODS_DIR env var
        run: echo "JAVAFX_JMODS_DIR=$(pwd)/javafx-jmods/javafx-jmods-24.0.1" >> $GITHUB_ENV

      - name: Set release notes fallback
        id: set_release_notes
        run: |
          if [ -z "${NOTES}" ]; then
            echo "release_notes=Automatically published release" >> $GITHUB_OUTPUT
          else
            echo "release_notes=${NOTES}" >> $GITHUB_OUTPUT
          fi
        env:
          NOTES: ${{ github.event.inputs.notes }}
        shell: bash

      - name: Determine platform name
        run: |
          case "${{ matrix.os }}" in
            ubuntu-latest) echo "PACKAGE_PLATFORM=linux" ;; 
            macos-latest) echo "PACKAGE_PLATFORM=mac" ;; 
            windows-latest) echo "PACKAGE_PLATFORM=windows" ;; 
          esac >> $GITHUB_ENV
        shell: bash

      - name: Package Native Executable
        run: |
          VERSION="${{ github.event.inputs.version }}"
          mvn clean package \
            -Drevision="$VERSION" \
            -Djdk.path="$JAVA_HOME" \
            -Dpackage.platform="$PACKAGE_PLATFORM" \
            -Djavafx.module.path="$JAVAFX_JMODS_DIR"
        shell: bash

      - name: Name build artifacts
        run: |
          ARCH="${{ matrix.arch }}"
          VERSION="${{ github.event.inputs.version }}"
          NAME="${{ github.event.repository.name }}"
          PLATFORM="${PACKAGE_PLATFORM}"

          # Linux
          if [ "$PLATFORM" = "linux" ]; then
            mv target/${NAME}_${VERSION}.AppImage target/${NAME}_${VERSION}_${ARCH}.AppImage || true
            mv target/${NAME}_${VERSION}.deb target/${NAME}_${VERSION}_${ARCH}.deb || true
            mv target/${NAME}_${VERSION}.rpm target/${NAME}_${VERSION}_${ARCH}.rpm || true
            mv target/${NAME}-${VERSION}-linux.zip target/${NAME}_${VERSION}_linux_${ARCH}.zip || true
          fi

          # macOS
          if [ "$PLATFORM" = "mac" ]; then
            mv target/${NAME}_${VERSION}.dmg target/${NAME}_${VERSION}_${ARCH}.dmg || true
            mv target/${NAME}_${VERSION}.pkg target/${NAME}_${VERSION}_${ARCH}.pkg || true
            mv target/${NAME}-${VERSION}-mac.zip target/${NAME}_${VERSION}_mac_${ARCH}.zip || true
          fi

          # Windows
          if [ "$PLATFORM" = "windows" ]; then
            mv target/${NAME}_${VERSION}.exe target/${NAME}_${VERSION}_${ARCH}.exe || true
            mv target/${NAME}_${VERSION}.msi target/${NAME}_${VERSION}_${ARCH}.msi || true
            mv target/${NAME}_${VERSION}.msm target/${NAME}_${VERSION}_${ARCH}.msm || true
            mv target/${NAME}-${VERSION}-windows.zip target/${NAME}_${VERSION}_windows_${ARCH}.zip || true
          fi
        shell: bash

      - name: Publish release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.set_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
          files: |
            target/${NAME}_${VERSION}_${ARCH}.*
            target/${NAME}_${VERSION}_*-${ARCH}.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
