name: Build and Release Native Packages

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (Semantic version, e.g. 1.2.3)'
        required: true
        type: string
      notes:
        description: 'Release notes'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Download JavaFX JMods 24.0.1
        run: |
          OS="${{ matrix.os }}"
          ARCH="${{ matrix.arch }}"

          case "$OS" in
            ubuntu-latest)
              if [ "$ARCH" = "arm64" ]; then
                JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_linux-aarch64_bin-jmods.zip"
              else
                JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_linux-x64_bin-jmods.zip"
              fi
              ;;
            macos-latest)
              if [ "$ARCH" = "arm64" ]; then
                JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_osx-aarch64_bin-jmods.zip"
              else
                JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_osx-x64_bin-jmods.zip"
              fi
              ;;
            windows-latest)
              JFX_URL="https://download2.gluonhq.com/openjfx/24.0.1/openjfx-24.0.1_windows-x64_bin-jmods.zip"
              ;;
            *)
              echo "Unsupported OS: $OS"
              exit 1
              ;;
          esac

          echo "Downloading JavaFX JMods from $JFX_URL"
          curl -L "$JFX_URL" -o javafx-jmods.zip
          unzip javafx-jmods.zip -d javafx-jmods
          rm javafx-jmods.zip
        shell: bash

      - name: Set JAVAFX_JMODS_DIR env var
        run: echo "JAVAFX_JMODS_DIR=$(pwd)/javafx-jmods/javafx-jmods-24.0.1" >> $GITHUB_ENV
        shell: bash

      - name: Install Inno Setup (ISCC)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $url = 'https://jrsoftware.org/download.php/is.exe'
          $output = "$env:TEMP\is.exe"
          Invoke-WebRequest $url -OutFile $output
          Start-Process -FilePath $output -ArgumentList '/VERYSILENT', '/SUPPRESSMSGBOXES', '/NORESTART', '/SP-' -Wait

          # Add to PATH for current session
          $innoPath = "${env:ProgramFiles(x86)}\Inno Setup 6"
          echo "$innoPath" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Set release notes fallback
        id: set_release_notes
        run: |
          if [ -z "${NOTES}" ]; then
            echo "release_notes=Automatically published release" >> $GITHUB_OUTPUT
          else
            echo "release_notes=${NOTES}" >> $GITHUB_OUTPUT
          fi
        env:
          NOTES: ${{ github.event.inputs.notes }}
        shell: bash

      - name: Determine platform name
        run: |
          case "${{ matrix.os }}" in
            ubuntu-latest) echo "PACKAGE_PLATFORM=linux" ;; 
            macos-latest) echo "PACKAGE_PLATFORM=mac" ;; 
            windows-latest) echo "PACKAGE_PLATFORM=windows" ;; 
          esac >> $GITHUB_ENV
        shell: bash

      - name: Package Native Executable
        run: |
          VERSION="${{ github.event.inputs.version }}"
          mvn clean package \
            -Drevision="$VERSION" \
            -Djdk.path="$JAVA_HOME" \
            -Dpackage.platform="$PACKAGE_PLATFORM" \
            -Djavafx.module.path="$JAVAFX_JMODS_DIR"
        shell: bash

      - name: Name build artifacts
        run: |
          ARCH="${{ matrix.arch }}"
          VERSION="${{ github.event.inputs.version }}"
          NAME="${{ github.event.repository.name }}"
          PLATFORM="${PACKAGE_PLATFORM}"

          # Linux
          if [ "$PLATFORM" = "linux" ]; then
            mv target/${NAME}_${VERSION}.AppImage target/${NAME}_${VERSION}_linux_${ARCH}.AppImage || true
            mv target/${NAME}_${VERSION}.deb target/${NAME}_${VERSION}_linux_${ARCH}.deb || true
            mv target/${NAME}_${VERSION}.rpm target/${NAME}_${VERSION}_linux_${ARCH}.rpm || true
            mv target/${NAME}-${VERSION}-linux.zip target/${NAME}_${VERSION}_linux_${ARCH}.zip || true
          fi

          # macOS
          if [ "$PLATFORM" = "mac" ]; then
            mv target/${NAME}_${VERSION}.dmg target/${NAME}_${VERSION}_mac_${ARCH}.dmg || true
            mv target/${NAME}_${VERSION}.pkg target/${NAME}_${VERSION}_mac_${ARCH}.pkg || true
            mv -r target/${NAME}/${NAME}.app target/${NAME}_${VERSION}_mac_${ARCH}.app || true
          fi

          # Windows
          if [ "$PLATFORM" = "windows" ]; then
            mv target/${NAME}_${VERSION}.exe target/${NAME}_${VERSION}_windows_${ARCH}.exe || true
            mv target/${NAME}_${VERSION}.msi target/${NAME}_${VERSION}_windows_${ARCH}.msi || true
            mv target/${NAME}_${VERSION}.msm target/${NAME}_${VERSION}_windows_${ARCH}.msm || true
          fi
        shell: bash

      - name: Publish release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.set_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
          files: |
            target/${{ github.event.repository.name }}_${{ github.event.inputs.version }}_*_${{ matrix.arch }}.*
          overwrite_files: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
